### ISSUE TITLE
Australia->WA case numbers are wrong

### ISSUE THREAD

**Issue by guyk** [alext234/coronavirus-stats#11]
I can vouch for the accuracy of all Australian states with the exception of WA which looks clearly wrong.

**Comment by guyk** [comment]
Wanted to thank you for your efforts too: I've personally used this data to convince somewhere between 3-10 people that covid-19 is a serious health emergency.

**Comment by alext234** [comment]
@guyk I’ll have a look. The health website is changed quite often and that confuses the scrapper code quite a bit :)

**Comment by alext234** [comment]
Removed data for WA where values are not cleared.
