### ISSUE TITLE
Australia Stats send too much data in CSV 1st line

### ISSUE THREAD

**Issue by nuffty** [alext234/coronavirus-stats#12]
1st line with deffinition is also sending extra details.
**"*Note that under National Notifiable Diseases Surveillance System reporting requirements, cases are reported based on their Australian jurisdiction of residence rather than where they were detected. For example, a case reported previously in the NT in a NSW resident is counted in the national figures as a NSW case. **Includes Diamond Princess repatriation cases: Qld (3), SA (1), Vic (4), WA (2, including 1 death)",**act,australia,date,nsw,nt,qld,sa,tas,victoria,wa

**Comment by alext234** [comment]
@nuffty Thanks. It's fixed now but feel free to reopen if it comes back. The gov changes the website quite often !
